---
title: "Beta-Binomial Bayesian model"
author: "P. Nicol"
date: "8/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading the data

```{r}
Sco <- readRDS("/Users/phillipnicol/Desktop/local_files/data/scDiffPopDATA/gse145281_tumor/KIRC_GSE145281_aPD1_CCA_res.RDS")
Sco <- Sco$RNA
```

```{r}
library(SingleR)

immune_ref <- MonacoImmuneData()

annotation <- SingleR(test = Sco@assays$RNA@counts, ref = immune_ref@assays@data$logcounts, labels = immune_ref$label.fine)
```


```{r}
Sco@meta.data$CellType <- annotation$first.labels
```

```{r}
DimPlot(Sco, group.by = "CellType", label = TRUE) + NoLegend()
```

## Make hierarchical clustering tree out of Monaco immune tree

```{r}
library(dplyr)
library(magrittr)
library(data.table)

ref.data <-  immune_ref 
col.dat = ref.data@colData %>% as.data.table %>% 
  .[,label.fine:=as.factor(label.fine)]  %>% 
  .[,label.main:=as.factor(label.main)]
create.psuedobulk <- function(exp.mat, labels) {
  dt1 = data.table(V1=labels)
  one.hot = mltools::one_hot(dt1) %>% as.matrix
  one.hot %>% colMeans %>% 
    sweep(one.hot,., MARGIN = 2, FUN = "/")
  out = exp.mat %*% one.hot
  out %>% set_colnames(gsub("V1_", colnames(one.hot), replacement = ""))
}
ref.psuedo.main = create.psuedobulk(ref.data@assays@data$logcounts, col.dat$label.main)
d = 1 -cor(ref.psuedo.main[,1:3], method = "spearman")
hc1 <- hclust(dist(d), method = "complete" )
plot(hc1, cex = 0.6, hang = -1, main="Monaco main")
ref.psuedo.fine = create.psuedobulk(ref.data@assays@data$logcounts, col.dat$label.fine)
d = 1 -cor(ref.psuedo.fine, method = "spearman")
hc1 <- hclust(dist(d), method = "complete" )
plot(hc1, cex = 0.6, hang = -1, main="Monaco fine")
```



```{r}
Tree <- as_edgelist(G)
```


```{r}
DFS <- function(Tree, node) {
  if(node == 0) {
    return(CellTypes)
  }
  
  leaves <- c() 
  
  row <- Tree[node,]
  
  allchild <- which(Tree[,1] == row[2])
  
  for(child in allchild) {
    leaves <- c(leaves, DFS(Tree, child))
  }
  
  if(length(allchild) == 0) {
    return(row[2])
  }
  
  return(leaves)
}
```



## Grab the counts

```{r}
patient_types <- unique(Sco@meta.data$sample)

CellTypes <- unique(Sco@meta.data$CellType)

Blood <- data.frame(matrix(0, ncol = 8, nrow = length(CellTypes)))
rownames(Blood) <- CellTypes; colnames(Blood) <- c(1:8)

Tumor <- data.frame(matrix(0, ncol = 8, nrow = length(CellTypes)))
rownames(Tumor) <- CellTypes; colnames(Tumor) <- c(1:8)

cnt_i <- 1
for(i in patient_types) {
  cnt_j <- 1
  Sco_sub <- Sco@meta.data[Sco@meta.data$sample == i,]$CellType
  for(j in CellTypes) {
    if(grepl("Blood", i)) {
      Blood[cnt_j, 2*cnt_i-1] <- length(which(Sco_sub == j))
      Blood[cnt_j, 2*cnt_i] <- length(Sco_sub)
      cnt_j <- cnt_j + 1 
    }
    else {
      Tumor[cnt_j, 2*cnt_i-1] <- length(which(Sco_sub == j))
      Tumor[cnt_j, 2*cnt_i] <- length(Sco_sub)
      cnt_j <- cnt_j + 1 
    }
  }
  cnt_i <- cnt_i + 1 
  if(cnt_i == 5) {cnt_i = 1}
}

Blood[12,3] <- 1
```





```{r}
library(bang)

for(i in 1:nrow(Tree)) {
  subtree <- DFS(Tree,i)
  
  ix <- which(Tree[,2] == Tree[i,1])
  if(length(ix) == 0) {next}
  tree <- DFS(Tree,ix)
  
  
  sub <- which(rownames(Blood) %in% subtree)
  sub2 <- which(rownames(Blood) %in% tree)

  data <- colSums(Blood[sub,])[c(1,3,5,7)]
  data2 <- colSums(Blood[sub2,])[c(1,3,5,7)]

  df_blood <- cbind(data,data2)
  
  sub <- which(rownames(Tumor) %in% subtree)
  sub2 <- which(rownames(Tumor) %in% tree)

  data <- colSums(Tumor[sub,])[c(1,3,5,7)]
  data2 <- colSums(Tumor[sub2,])[c(1,3,5,7)]
  
  df_tumor <- cbind(data,data2)
  
  print(df_tumor)
  print(df_blood)
  
  badcheck <- which(rowSums(df_blood) == 0)
  df_blood[badcheck,2] <- 1
  badcheck <- which(rowSums(df_tumor) == 0)
  df_tumor[badcheck,2] <- 1
  
  if(sum(df_blood[,1]) == 0) {df_blood[1,1] <- 1}
  if(sum(df_tumor[,1]) == 0) {df_tumor[1,1] <- 1}
  
  if(identical(df_blood[,1], df_blood[,2])) {df_blood[1,1] <- df_blood[1,1]-1}
  if(identical(df_tumor[,1], df_tumor[,2])) {df_tumor[1,1] <- df_tumor[1,1]-1}
  
  res_blood <- hef(model = "beta_binom", data = df_blood,  n = 1000)
  res_tumor <- hef(model = "beta_binom", data = df_tumor, n = 1000) 
  
  colnames(res_blood$theta_sim_vals) <- c("B1", "B2", "B3", "B4")
  colnames(res_tumor$theta_sim_vals) <- c("T1", "T2", "T3", "T4")
  
  BloodSamps <- sample(res_blood$theta_sim_vals, 1000, replace = TRUE)
  TumorSamps <- sample(res_tumor$theta_sim_vals, 1000, replace = TRUE)
  Samps <- BloodSamps - TumorSamps
  
  
  tumorupper <- apply(res_tumor$theta_sim_vals, 2, function(x) quantile(x,0.75))
  bloodupper <- apply(res_blood$theta_sim_vals, 2, function(x) quantile(x,0.75))
  tumorlower <- apply(res_tumor$theta_sim_vals, 2, function(x) quantile(x,0.25))
  bloodlower <- apply(res_blood$theta_sim_vals, 2, function(x) quantile(x,0.25))
  
  TumorGap <- min(tumorlower) - max(bloodupper)
  BloodGap <- min(bloodlower) - max(tumorupper)
  TumorGap <- round(TumorGap,2); BloodGap <- round(BloodGap,2)
  
  
  blood_meds <- apply(res_blood$theta_sim_vals, 2, median)
  tumor_meds <- apply(res_tumor$theta_sim_vals, 2, median)
  
  
  wp <- wilcox.test(blood_meds, tumor_meds)$p.value
  wp <- round(wp, 2)
  
  graphics::boxplot(cbind(res_blood$theta_sim_vals, res_tumor$theta_sim_vals), col = c(rep("red", 4), rep("blue", 4)), main = i, ylab = "Theta", xlab = paste("Wilcox: ", wp, "TumorGap: ", TumorGap, "BloodGap:", BloodGap))
paste("/Users/phillipnicol/Desktop/local_files/data/scDiffPopDATA/gse145281_tumor/Bayesian_model/", i, ".png", sep = "")
  hist(Samps)
}
```








## Bayesian anaylsis 
```{r}
library(bang)

for(i in CellTypes) {
  ix <- which(rownames(Blood) == i)
  
  df_blood <- data.frame(matrix(0, nrow = 4, ncol = 2))
  df_blood[,1] <- t(Blood[ix,c(1,3,5,7)])
  df_blood[,2] <- t(Blood[ix,c(2,4,6,8)])

  df_tumor <- data.frame(matrix(0, nrow = 4, ncol = 2))
  df_tumor[,1] <- t(Tumor[ix,c(1,3,5,7)])
  df_tumor[,2] <- t(Tumor[ix,c(2,4,6,8)]) 
  
  res_blood <- hef(model = "beta_binom", data = df_blood,  n = 1000)
  res_tumor <- hef(model = "beta_binom", data = df_tumor, n = 1000) 
  
  colnames(res_blood$theta_sim_vals) <- c("B1", "B2", "B3", "B4")
  colnames(res_tumor$theta_sim_vals) <- c("T1", "T2", "T3", "T4")
  
  tumorupper <- apply(res_tumor$theta_sim_vals, 2, function(x) quantile(x,0.75))
  bloodupper <- apply(res_blood$theta_sim_vals, 2, function(x) quantile(x,0.75))
  tumorlower <- apply(res_tumor$theta_sim_vals, 2, function(x) quantile(x,0.25))
  bloodlower <- apply(res_blood$theta_sim_vals, 2, function(x) quantile(x,0.25))
  
  TumorGap <- min(tumorlower) - max(bloodupper)
  BloodGap <- min(bloodlower) - max(tumorupper)
  TumorGap <- round(TumorGap,2); BloodGap <- round(BloodGap,2)
  
  
  blood_meds <- apply(res_blood$theta_sim_vals, 2, median)
  tumor_meds <- apply(res_tumor$theta_sim_vals, 2, median)
  
  
  wp <- wilcox.test(blood_meds, tumor_meds)$p.value
  wp <- round(wp, 2)
  
  graphics::boxplot(cbind(res_blood$theta_sim_vals, res_tumor$theta_sim_vals), col = c(rep("red", 4), rep("blue", 4)), main = i, ylab = "Theta", xlab = paste("Wilcox: ", wp, "TumorGap: ", TumorGap, "BloodGap:", BloodGap))
paste("/Users/phillipnicol/Desktop/local_files/data/scDiffPopDATA/gse145281_tumor/Bayesian_model/", i, ".png", sep = "")
  png(filename = paste("/Users/phillipnicol/Desktop/local_files/data/scDiffPopDATA/gse145281_tumor/Bayesian_model/", i, ".png", sep = ""), width = 2*480)
}
```


```{r, eval = FALSE}
library(bang) 

Scores <- data.frame(matrix(0, nrow = length(CellTypes), ncol = 1))
rownames(Scores) <- CellTypes; colnames(Scores) <- 1

cnt <- 1
for(i in CellTypes) {
  ix <- which(rownames(Blood) == i)
  
  df_blood <- data.frame(matrix(0, nrow = 4, ncol = 2))
  df_blood[,1] <- t(Blood[ix,c(1,3,5,7)])
  df_blood[,2] <- t(Blood[ix,c(2,4,6,8)])

  df_tumor <- data.frame(matrix(0, nrow = 4, ncol = 2))
  df_tumor[,1] <- t(Tumor[ix,c(1,3,5,7)])
  df_tumor[,2] <- t(Tumor[ix,c(2,4,6,8)]) 
  
  res_blood <- hef(model = "beta_binom", data = df_blood,  n = 1000)
  res_tumor <- hef(model = "beta_binom", data = df_tumor, n = 1000)
  
  Scores[cnt,] <- sum(sapply(c(1:1000), function(x) {
    alpha_1 <- res_blood$sim_vals[x,1]; beta_1 <- res_blood$sim_vals[x,2]
    X1 <- rbeta(1, alpha_1, beta_1)
    alpha_1 <- res_tumor$sim_vals[x,1]; beta_1 <- res_tumor$sim_vals[x,2]
    X2 <- rbeta(1, alpha_1, beta_1)
    if(X2 > X1) {
      return(1)
    }
    else{
      return(0)
    }
  }))/1000
  
  cnt <- cnt + 1
}
```


## Appendix

```{r}
sessionInfo()
```

