---
title: "Single-Cell Differential Immune Population Analysis"
author: "Danielle Paulson"
date: "July 25, 2020"
output: 
  html_notebook:
    toc: true
    toc_float: true
---

# Load packages

```{r message = FALSE}
library(Seurat)
library(dplyr)
library(tidyr)
library(ggplot2)
library(magrittr)
library(Matrix)
library(cowplot)
library(tidyverse)
library(uwot)
library(parallel)
library(data.tree)
library(DiagrammeR)
library(rare)
library(data.table)
library(clusterProfiler)
```

# Load data

```{r}
GSE145281 <- readRDS("Desktop/seurat (1).RDS")
sco <- GSE145281
```

# UMAP with annotated clusters

```{r}
annotations <- readRDS("Desktop/cell.annotations (1).RDS")
annotations
```
```{r}
table(annotations$HumanPrimaryCellAtlasData.main)
```

```{r}
table(sco@active.ident)
```

```{r}
DimPlot(sco, reduction = "umap", label = TRUE)
```
```{r}
new.cluster.ids <- c("Monocyte", "T_cells", "NK_cell", "B_cell", "Pre-B_cell_CD34-", "BM", "Neutrophils", "Erythroblast", "Platelets", "Pro-B_cell_CD34+", "HSC_-G-CSF", "CMP", "GMP", "DC", "BM & Prog.", "Macrophage", "MEP")
names(new.cluster.ids) <- levels(sco)
sco <- RenameIdents(sco, new.cluster.ids)
DimPlot(sco, reduction = "umap", label = TRUE, pt.size = 1) + NoLegend()
```

# K-means clustering tree

## Create tree matrix

```{r}
create.tree <- function(object, reduction='pca', dims=NULL, oldk = 1, newk = 2) {
    object
     embeddings <- Embeddings(object = object, reduction = reduction)[, dims]
     km = kmeans(embeddings, centers = 2, iter.max = 10)$cluster
     seurat.clust = object$seurat_clusters
     out = sapply(unique(seurat.clust), function(tt){
         aa = table(km[seurat.clust==tt]) %>% which.max() %>%
         names() 
         ifelse(aa=="1", oldk, newk)
     }) 
     names(out) = unique(seurat.clust)
     
     if(length(unique(out))==1) out[] = oldk
     out
}
```

```{r}
create.cluster.tree <- function(sco) {
    require(plyr)
    old.clusters.id = unique(sco$seurat_clusters) %>% as.character
    new.clusters.id = seq(length(old.clusters.id))
    sco$seurat_clusters = mapvalues(sco$seurat_clusters, from = old.clusters.id, to = new.clusters.id)
    seurat.clusters = new.clusters.id
    maxk = length(unique(sco$seurat_clusters))
    clust.mat = matrix(NA, ncol=maxk, nrow=maxk)
    rownames(clust.mat) = paste0("clust", old.clusters.id) 
    clust.mat[,1] = 1
    for (ii in seq(1,maxk-1)) {
        clust.mat.old = clust.mat[, ii] 
        temp =  table(clust.mat.old) 
        temp = temp[temp > 1]
        if(length(temp) == 0){ 
            break
        }
        oldk = which.max(temp) %>% 
        names() %>% as.numeric() %>% min()
        newk=max(clust.mat[,ii]) +1
        if(oldk >= maxk){ 
            break
        }
        seurat.clust.old = seurat.clusters[clust.mat.old == oldk] %>% as.character
        inx = which(seurat.clusters == oldk)
        out = create.tree(sco[,sco$seurat_clusters %in% seurat.clust.old], reduction="pca", oldk, newk, dims = 1:20)
        out = out[seurat.clust.old]
        clust.mat[, ii+1] = clust.mat[,ii]
        old.clusters.id.curr = old.clusters.id[as.numeric(names(out))]
        clust.mat[paste0("clust", old.clusters.id.curr),ii+1] = unlist(out)
    }
    clust.mat%>% t() %>%
        unique() %>% t()
}

```

```{r}
clust.mat = create.cluster.tree(sco)
clust.mat
```

## Visualize with dendrogram

```{r}
df <- as.data.frame((clust.mat), row.names = c('clust13', 'clust11', 'clust1', 'clust0', 'clust8', 'clust15', 'clust9', 'clust5', 'clust2', 'clust3', 'clust7', 'clust6', 'clust14', 'clust10', 'clust4', 'clust12', 'clust16'))
df
```
```{r}
d <- dist(df, method = "euclidean")
hc <- hclust(d, method = "complete")
plot(hc, cex = 0.6, hang = -1)
```

```{r}
df2 <- as.data.frame((clust.mat), row.names = c('DC', 'CMP', 'T_cells', 'Monocyte', 'Platelets', 'Macrophage', 'Pro-B_cell_CD34+', 'BM', 'NK_cell', 'B_cell', 'Erythroblast', 'Neutrophils', 'BM & Prog.', 'HSC_-G-CSF', 'Pre-B_cell_CD34-', 'GMP', 'MEP'))
df2
```

```{r}
d2 <- dist(df2, method = "euclidean")
hc2 <- hclust(d2, method = "complete")
plot(hc2, cex = 0.6, hang = -1)
```
# Hierarchical clustering pseudobulk analysis

```{r}
cluster.averages <- AverageExpression(sco)
cluster.averages
```

```{r}
df3 <- do.call(rbind.data.frame, cluster.averages)
df3
```

```{r}
df3 <- data.frame(t(df3))
df3
```

```{r}
rownames(df3) = c('Monocyte', 'T_cells', 'NK_cell', 'B_cell', 'Pre-B_cell_CD34-', 'BM', 'Neutrophils', 'Erythroblast', 'Platelets', 'Pro-B_cell_CD34+', 'HSC_-G-CSF', 'CMP', 'GMP', 'DC', 'BM & Prog.', 'Macrophage', 'MEP')
df3
```

```{r}
# Dissimilarity matrix
d3 <- dist(df3, method = "euclidean")

# Hierarchical clustering using Complete Linkage
hc3 <- hclust(d3, method = "complete" )

# Plot the obtained dendrogram
plot(hc3, cex = 0.6, hang = -1)
```

# Tree differential expression analysis

## Identify differentially expressed genes

```{r}
DESeq2DETest <- function(
  data.use,
  cells.1,
  cells.2,
  verbose = TRUE,
  ...
) {
  # if (!PackageCheck('DESeq2', error = FALSE)) {
  #   stop("Please install DESeq2 - learn more at https://bioconductor.org/packages/release/bioc/html/DESeq2.html")
  # }
  group.info <- data.frame(row.names = c(cells.1, cells.2))
  group.info[cells.1, "group"] <- "Group1"
  group.info[cells.2, "group"] <- "Group2"
  group.info[, "group"] <- factor(x = group.info[, "group"])
  group.info$wellKey <- rownames(x = group.info)
  dds1 <- DESeq2::DESeqDataSetFromMatrix(
    countData = data.use,
    colData = group.info,
    design = ~ group
  )
  dds1 <- DESeq2::estimateSizeFactors(object = dds1)
  dds1 <- DESeq2::estimateDispersions(object = dds1, fitType = "local")
  dds1 <- DESeq2::nbinomWaldTest(object = dds1)
  res <- DESeq2::results(
    object = dds1,
    contrast = c("group", "Group1", "Group2"),
    alpha = 0.05,
    ...
  )
  # to.return <- data.frame(p_val = res$pvalue, row.names = rownames(res))
  return(res)
}
```

```{r}
mydeg <- function(sco.curr) {
    exp.curr1 = sco.curr@assays$RNA@counts[sco.curr@assays$RNA@var.features,]
    meta.dt1 = sco.curr@meta.data %>%
        as.data.table() %>%
        .[,.(binaryResponse=response, patient=patient)] 
    
    meta.curr = list()
    exp.curr2 = list()
    for(patient in unique(meta.dt1$patient)){
        inx = which(meta.dt1$patient==patient)
        exp.curr2[[patient]] = rowSums(exp.curr1[,inx],na.rm=T)
        meta.curr[[patient]] = meta.dt1[inx[1],]
    }
    meta.dt = do.call(rbind, meta.curr)
    exp.curr = t(do.call(rbind, exp.curr2))
    responders = meta.dt[binaryResponse==1]$patient
    nonresponders = meta.dt[binaryResponse==0]$patient
    deseq.out = DESeq2DETest(data.use=exp.curr[,c(responders,nonresponders)], cells.1=responders, cells.2=nonresponders)
    deseq.dt = deseq.out %>%
        as.data.table() %>%
        mutate(gene=rownames(.)) %>%
        .[order(pvalue)] %>%
        .[,padj:=p.adjust(pvalue, method="fdr")]
    deseq.dt
}
```

## Identify enriched genes

```{r message = FALSE}
sco$binaryResponse =sco$response

# sco.sub = GSE145281[, GSE145281$seurat_clusters %in% c(10,11)]
responders.enrichment = nonresponders.enrichment = list()
seurat.clusters= unique(sco$seurat_clusters) %>% as.character
for (ii in seq(ncol(clust.mat) -1)) {
    clust.mat.old = clust.mat[, ii] 
    clust.mat.new = clust.mat[, ii+1] 
    temp =  table(clust.mat.old) 
    temp = temp[temp > 1]
    if(length(temp) == 0){ 
        break
    }
    ## finding group with most clusters
    oldk = which.max(temp) %>% 
    names() %>% as.numeric() %>% min()
    newk=max(clust.mat[,ii]) + 1
    
    seurat.clust.old = seurat.clusters[clust.mat.old == oldk] %>% as.character
    inx = which(seurat.clusters == oldk)
    sco.sub = sco[,sco$seurat_clusters %in% seurat.clust.old]%>%
     FindVariableFeatures(selection.method = "vst", nfeatures = 2000)
    
    ## Perform differential expression
    deg.curr = mydeg(sco.sub)
    deg.curr = deg.curr[padj<0.1]
    
    ## Find markers in children
    seurat.clust.cell.1 = seurat.clusters[clust.mat.new == oldk] %>% as.character
    Idents(sco.sub) = ifelse(sco.sub$seurat_clusters %in% seurat.clust.cell.1, 1 ,2) %>% as.factor
    markers.curr = FindAllMarkers(sco.sub, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25) ## this will give markers of both cell.1 (child1) and cell.2 (child2)
    markers.top  = markers.curr %>% group_by(cluster) %>% top_n(n = 200, wt = avg_logFC)
    term2gene  = markers.top %>%  as.data.table %>% 
    .[,.(term=cluster,gene=gene)] %>% as.data.frame
    
    ## perform enrichment see : https://yulab-smu.github.io/clusterProfiler-book/chapter3.html
    try({
      responders.enrichment[[ii]] = enricher(gene=deg.curr[log2FoldChange> 0]$gene, TERM2GENE = term2gene, pvalueCutoff=1)@result 
    })
    try({
    nonresponders.enrichment[[ii]] = enricher(gene=deg.curr[log2FoldChange< 0]$gene, TERM2GENE = term2gene, pvalueCutoff=1)@result
    })
}
```

```{r}
head(responders.enrichment)
```

```{r}
head(nonresponders.enrichment)
```

```{r}
sco$binaryResponse =sco$response
# sco.sub = GSE145281[, GSE145281$seurat_clusters %in% c(10,11)]
library(clusterProfiler)
responsders.enrichment = nonresponders.enrichment = list()
seurat.clusters= unique(sco$seurat_clusters) %>% as.character
for (ii in seq(ncol(clust.mat) -1)) {
    clust.mat.old = clust.mat[, ii] 
    clust.mat.new = clust.mat[, ii+1] 
    temp =  table(clust.mat.old) 
    temp = temp[temp > 1]
    if(length(temp) == 0){ 
        break
    }
    ## finding group with most clusters
    oldk = which.max(temp) %>% 
    names() %>% as.numeric() %>% min()
    newk=max(clust.mat[,ii]) + 1
    seurat.clust.old = seurat.clusters[clust.mat.old == oldk] %>% as.character
    inx = which(seurat.clusters == oldk)
    sco.sub = sco[,sco$seurat_clusters %in% seurat.clust.old]%>%
     FindVariableFeatures(selection.method = "vst", nfeatures = 2000)
    ## Perform differential expression
    deg.curr = mydeg(sco.sub)
    deg.curr = deg.curr[padj<0.1]
    ## Find markers in children
    seurat.clust.cell.1 = seurat.clusters[clust.mat.new == oldk] %>% as.character
    Idents(sco.sub) = ifelse(sco.sub$seurat_clusters %in% seurat.clust.cell.1, 1 ,2) %>% as.factor
    markers.curr = FindAllMarkers(sco.sub, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25) ## this will give markers of both cell.1 (child1) and cell.2 (child2)
    markers.top  = markers.curr %>% group_by(cluster) %>% top_n(n = 200, wt = avg_logFC)
    term2gene  = markers.top %>%  as.data.table %>% 
    .[,.(term=cluster,gene=gene)] %>% as.data.frame
    ## perform enrichment see : https://yulab-smu.github.io/clusterProfiler-book/chapter3.html
    try({
      responsders.enrichment[[ii]] = enricher(gene=deg.curr[log2FoldChange> 0]$gene, TERM2GENE = term2gene, pvalueCutoff=1)@result 
    })
    try({
    nonresponders.enrichment[[ii]] = enricher(gene=deg.curr[log2FoldChange< 0]$gene, TERM2GENE = term2gene, pvalueCutoff=1)@result
    })
}
```

```{r}
View(responsders.enrichment)
```









