## Tree differential expression analysis
```{r}
library(data.table)
library(magrittr)
library(ggplot2)
library(Matrix)
library(Seurat)
library(cowplot)
library(uwot)
library(parallel)
library(EnhancedVolcano)
library(tidyverse)
library(data.table)
```
```{r}
#' Function to perform differential expression. 
#'
#' @param sco 
#'
#' @return
#' @export
#'
#' @examples
mydeg <- function(sco) {
    exp.curr1 = sco@assays$RNA@counts
    meta.dt1 = sco@meta.data %>%
        as.data.table() %>%
        .[,.(binaryResponse=ifelse(response %in% c("CR", "PR"),1 ,0) , patient=patient.name)] 
    
    meta.curr = list()
    exp.curr2 = list()
    for(patient in unique(meta.dt1$patient)){
        inx = which(meta.dt1$patient==patient)
        exp.curr2[[patient]] = rowSums(exp.curr1[,inx],na.rm=T)
        meta.curr[[patient]] = meta.dt1[inx[1],]
    }
    meta.dt = do.call(rbind, meta.curr)
    exp.curr = t(do.call(rbind, exp.curr2))
    responders = meta.dt[binaryResponse==1]$patient
    nonresponders = meta.dt[binaryResponse==0]$patient
    deseq.out = DESeq2DETest(data.use=exp.curr[,c(responders,nonresponders)], cells.1=responders, cells.2=nonresponders)
    deseq.dt = deseq.out %>%
        as.data.frame() %>%
        mutate(gene=rownames(.)) %>%
        data.table() %>% 
        .[order(pvalue)]
    deseq.dt
}


```

# create tree stucture
```{r}
create.tree <- function(object, reduction='pca', dims=NULL, oldk = 1, newk = 2) {


    object
    
     embeddings <- Embeddings(object = object, reduction = reduction)[, dims]
     km = kmeans(embeddings, centers = 2, iter.max = 10)$cluster
     seurat.clust = object$seurat_clusters
     out = sapply(unique(seurat.clust), function(tt){
         aa = table(km[seurat.clust==tt]) %>% which.max() %>%
         names() 
         ifelse(aa=="1", oldk, newk)
     }) 
     names(out) = unique(seurat.clust)
     
     if(length(unique(out))==1) out[] = oldk
     out
}
# Function to create tree from seurat cluster. 
create.cluster.tree<- function(sco) {
    require(plyr)
    old.clusters.id = unique(sco$seurat_clusters) %>% as.character
    new.clusters.id = seq(length(old.clusters.id))
    sco$seurat_clusters = mapvalues(sco$seurat_clusters, from = old.clusters.id, to = new.clusters.id)
    seurat.clusters = new.clusters.id
    maxk = length(unique(sco$seurat_clusters))
    clust.mat = matrix(NA, ncol=maxk, nrow=maxk)
    rownames(clust.mat) = paste0("clust", old.clusters.id) 
    clust.mat[,1] = 1
    for (ii in seq(1,maxk-1)) {
        clust.mat.old = clust.mat[, ii] 
        temp =  table(clust.mat.old) 
        temp = temp[temp > 1]
        if(length(temp) == 0){ 
            break
        }
        oldk = which.max(temp) %>% 
        names() %>% as.numeric() %>% min()
        newk=max(clust.mat[,ii]) +1
        if(oldk >= maxk){ 
            break
        }
        seurat.clust.old = seurat.clusters[clust.mat.old == oldk] %>% as.character
        inx = which(seurat.clusters == oldk)
        out = create.tree(sco[,sco$seurat_clusters %in% seurat.clust.old], reduction="pca", oldk, newk, dims = 1:20)
        out = out[seurat.clust.old]
        clust.mat[, ii+1] = clust.mat[,ii]
        old.clusters.id.curr = old.clusters.id[as.numeric(names(out))]
        clust.mat[paste0("clust", old.clusters.id.curr),ii+1] = unlist(out)
    }
    clust.mat%>% t() %>%
        unique() %>% t()
}
library(Seurat)
sco = readRDS("<path>")
sco.sub = sco[,sample(ncol(sco),100)]
clust.mat.all = create.cluster.tree(sco.sub)
library(data.tree)
# acme <- Node$new("Acme Inc.")
  # accounting <- acme$AddChild("Accounting")


```


## calculate tree differential expression 
```{r}

cc = 1
lee.degs = list()
clust.inx = gsub("clust", rownames(clust.mat.all), replacement = "")
clust.mat.padded = cbind(clust.mat.all, as.factor(clust.inx))
# for (ii in seq(ncol(clust))) {
for (ii in c(1:6,17)) {
    clust.curr = clust.mat.padded[,ii]
    # for(jj in unique(clust.curr)) {
    for(jj in 8:12) {
        seurat.clust.curr = clust.inx[which(clust.curr==jj)]
        lee.degs[[cc]] = 
            tryCatch({
            sco[,(sco$seurat_clusters %in%seurat.clust.curr) & (sco$response %in% c("CR", "PD"))] %>%
            mydeg()}, error = function(e) NA)
        cc  = cc +1
    }
    print(cc)
}
# lee.degs.back = lee.degs

lee.deg.mat = lapply(lee.degs, function(tt){ 
    if(is.na(tt)) return(NULL)
    tt[match(lee.degs[[1]]$gene, gene)]$stat
    }) %>%
    do.call(cbind, .) %>%
    set_rownames(lee.degs[[1]]$gene)

## only include lymphocyte populations. 
aa =sco@reductions$umap@cell.embeddings 
lymp.deg = sco[,(aa[,1] > -10 &  aa[,2] < 10) & (sco$response %in% c("CR", "PD"))] %>% 
    mydeg()


sel.inx = which((aa[,1] > -10 &  aa[,2] < 10) & (sco$response %in% c("CR", "PD")) & (sco$Treatment.Cycle=="C1D1"))
lee.curr.pre  = sco[,sel.inx]
lymp.deg.pre = lee.curr.pre %>% 
    mydeg()

```


## Maestro annotations 
```{r}
library(MAESTRO)
GSE145281 = readRDS(file="~/liulab_home/data/single_cell/GSE145281/seurat.RDS") 

message("Identify cluster specific genes ...")
cluster.genes <- FindAllMarkersMAESTRO(object = GSE145281, min.pct = 0.1, logfc.threshold = 0.25, only.pos = TRUE)
cluster.genes <- cluster.genes[cluster.genes$p_val_adj< 1E-20, ]


# cell-type annotation


annot.result = data.table(colnames(GSE145281)) 
annot.result$HumanPrimaryCellAtlasData.fine = GSE145281$HumanPrimaryCellAtlasData.fine
annot.result$HumanPrimaryCellAtlasData.main = GSE145281$HumanPrimaryCellAtlasData.main
temp = RNAAnnotateCelltype(RNA = GSE145281,
                                  genes = cluster.genes,
                                  signatures = "human.immune.CIBERSORT",
                                  min.score = 0.6)
annot.result$cibersort = temp$assign.ident 

temp = RNAAnnotateCelltype(RNA = GSE145281,
                                  genes = cluster.genes,
                                  signatures = "mouse.all.facs.TabulaMuris",
                                  min.score = 0.6)
annot.result$mouse.all.facs.TabulaMuris = temp$assign.ident 
temp = RNAAnnotateCelltype(RNA = GSE145281,
                                  genes = cluster.genes,
                                  signatures = "mouse.all.droplet.TabulaMuris",
                                  min.score = 0.6)
annot.result$mouse.all.droplet.TabulaMuris  = temp$assign.ident 

saveRDS(file="~/liulab_home/data/single_cell/GSE145281/cell.annotations.RDS",annot.result)
```